<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="PRG_Test" Id="{e5eebc94-2583-419e-a5ae-15055f39621e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Test
VAR
	fbContextBuilder_Test	: FB_ContextBuilder_Test;
	
	fbScope			: FB_ScopedContext;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();


fbScope.Begin();

fbScope.End();
]]></ST>
    </Implementation>
    <LineIds Name="PRG_Test">
      <LineId Id="5" Count="0" />
      <LineId Id="14" Count="1" />
      <LineId Id="7" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>