##############################################################
# Description:
# This Pipeline is used to CI build the application
# It should check the code and run the tests in Pull Requests
##############################################################

# Pull Request Trigger
pr:
  branches:
    include:
    - master
    - main
    - dev

stages:
- stage: 'build'
  displayName: 'Build the applications'
  jobs:
  # log4TC
  - template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/log4tc/build-job.yaml
  # Documentation
  - template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/docs/build-job.yaml
