##############################################################
# Description:
# This Pipeline is used to build and release the application
# the artifacts are stored in GitHub Releases based on Tags
# with the pattern v*.*.* (e.g. V24.01.17)
#
# Also the documentation is generated and updated to the 
# github-pages branch with the name `github-pages` for the url
# https://mbc-engineering.github.io/log4TC/
##############################################################

# Build Trigger
trigger:
  tags:
    include:
      - v*
stages:
# # ╔════════════════════════╗
# # ║ Build Stage            ║
# # ╚════════════════════════╝
# - stage: 'Build'
#   displayName: 'Build the application'
#   jobs: 
#   - job: 'Build'
#     displayName: 'Build job'
#     # Cake script uses MSBuild .UseToolVersion(MSBuildToolVersion.VS2019)
#     pool:
#       vmImage: 'windows-2019'
#     steps:
#     - checkout: self
#       submodules: recursive      
#     - template: .azure-pipelines/templates/build.yml

# ╔════════════════════════╗
# ║ PublishTag Stage       ║
# ╚════════════════════════╝

- stage: 'PublishTag'
  displayName: 'Publish to github Tag'
  #dependsOn: Build
  #condition:  succeeded()
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-latest'
    environment: publish-github
    # see: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/create-multistage-pipeline?view=azure-devops#add-instance-variables
    variables:
    - group: publish-github-vg
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none          
          #- download: current
          #  artifact: drop
          #- download: mbc-engineering.log4TC
          #  artifact: drop
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'specific'
              project: '5542496b-1239-4d74-a233-9da3b0388d39'
              pipeline: '20'
              specificBuildWithTriggering: true
              buildVersionToDownload: 'latest'
              downloadType: 'specific'
              downloadPath: '$(Pipeline.Workspace)/drop'
              cleanDestinationFolder: true
          - powershell: ls $(Pipeline.Workspace)/drop
            displayName: 'list artifact files'            
          - task: GitHubRelease@1
            displayName: 'Create GitHub Releases'
            inputs:
              gitHubConnection: 'github.com_bqstony'
              repositoryName: 'mbc-engineering/log4TC'
              action: 'create'
              target: '$(Build.SourceVersion)'
              #tagSource: 'gitTag'
              #tagPattern: 'v*'
              tagSource: 'userSpecifiedTag'
              tag: 'vTest'
              releaseNotesSource: 'inline'
              assets: '$(Pipeline.Workspace)/drop/msi/**'
              addChangeLog: false