##############################################################
# Description:
# This Pipeline is used to build and release the application
# the artifacts are stored in GitHub Releases based on Tags
# with the pattern v*.*.* (e.g. V24.01.17)
#
# Also the documentation is generated and updated to the
# github-pages branch with the name `github-pages` for the url
# https://mbc-engineering.github.io/log4TC/
##############################################################

# Build Trigger when new tag created that starts with v
trigger:
  tags:
    include:
    - v*

# Disable PR Trigger
pr: none

# Define repositories that can be used
resources:
  repositories:
  - repository: gh-pages-repo
    type: github
    endpoint: github.com_bqstony
    name: mbc-engineering/log4TC
    ref: gh-pages
  - repository: deb-repo-repo
    type: github
    endpoint: github.com_bqstony
    name: mbc-engineering/log4TC
    ref: deb-repo
  # self is the trigger repo + branch

stages:
# ╔════════════════════════╗
# ║ Build Stage            ║
# ╚════════════════════════╝
- stage: 'build'
  displayName: 'Build the applications'
  jobs:
  # log4TC
  - template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/log4tc/build-job.yaml
  # Documentation
  - template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/docs/build-job.yaml
  # tclibrary
  - template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/tclibrary/build-job.yaml

# ╔════════════════════════╗
# ║ PublishRelease         ║
# ╚════════════════════════╝
- stage: 'PublishRelease'
  displayName: 'Publish to github Tag'
  dependsOn: Build
  #condition:  succeeded()
  condition: false
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-latest'
    environment: publish-github
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - download: current
            artifact: msi
          - download: current
            artifact: tclibrary
          - download: current
            artifact: log4TC-linux-x64
          - download: current
            artifact: log4TC-linux-arm64
          # For easy testing comment out the above and uncomment the below
          # - task: DownloadBuildArtifacts@1
          #   inputs:
          #     buildType: 'specific'
          #     project: '5542496b-1239-4d74-a233-9da3b0388d39'
          #     pipeline: '20'
          #     specificBuildWithTriggering: true
          #     buildVersionToDownload: 'latest'
          #     downloadType: 'specific'
          #     downloadPath: '$(Pipeline.Workspace)/msi'
          #     cleanDestinationFolder: true

          - powershell: Get-ChildItem -Force -Path $(Pipeline.Workspace)/msi
            displayName: 'list artifact files'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Pipeline.Workspace)/log4TC-linux-x64'
              archiveType: 'tar'
              tarCompression: 'gz'
              archiveFile: '$(Build.ArtifactStagingDirectory)/log4TC-linux-x64.tgz'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Pipeline.Workspace)/log4TC-linux-arm64'
              archiveType: 'tar'
              tarCompression: 'gz'
              archiveFile: '$(Build.ArtifactStagingDirectory)/log4TC-linux-arm64.tgz'

          - task: GitHubRelease@1
            displayName: 'Create GitHub Releases'
            inputs:
              gitHubConnection: 'github.com_bqstony'
              repositoryName: 'mbc-engineering/log4TC'
              action: 'create'
              target: '$(Build.SourceVersion)'
              # Pattern check does not work for me
              #tagSource: 'gitTag'
              #tagPattern: 'v*'
              tagSource: 'userSpecifiedTag'
              tag: '$(Build.SourceBranchName)' # The PR, Branch or Tag Name
              releaseNotesSource: 'inline'
              assets: |
                $(Pipeline.Workspace)/msi/**
                $(Pipeline.Workspace)/tclibrary/**
                $(Build.ArtifactStagingDirectory)/**
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'

- stage: 'PublishGitHubPages'
  displayName: 'Publish to github pages'
  dependsOn: PublishRelease
  # condition:  succeeded()
  condition: false
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-latest'
    environment: publish-github-pages
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: docs
          # For easy testing comment out the above and uncomment the below
          # - task: DownloadBuildArtifacts@1
          #   inputs:
          #     buildType: 'specific'
          #     project: '5542496b-1239-4d74-a233-9da3b0388d39'
          #     pipeline: '20'
          #     specificBuildWithTriggering: true
          #     buildVersionToDownload: 'latest'
          #     downloadType: 'specific'
          #     downloadPath: '$(Pipeline.Workspace)/docs'
          #     cleanDestinationFolder: true

          - powershell: Get-ChildItem -Force -Path $(Pipeline.Workspace)/docs
            displayName: 'list artifact files in workspace=$(Pipeline.Workspace)'
          - checkout: gh-pages-repo
            submodules: recursive
            persistCredentials: true
          - script: |
              git config user.email "AutomatedDeploy@bot.com"
              git config user.name "AutomatedDeploy"
              git fetch
              git status
              git branch -a
              git remote -v
              git checkout gh-pages
            displayName: 'prepare git repo'
            workingDirectory: '$(Build.SourcesDirectory)'
          - task: PowerShell@2
            displayName: 'Clear old files in gh-pages branch'
            inputs:
              targetType: 'inline'
              script: |
                # Get all files and subdirectories except the .git directory
                $itemsToDelete = Get-ChildItem | Where-Object { $_.Name -ne ".git" }

                # Delete files and subdirectories
                foreach ($item in $itemsToDelete) {
                    Remove-Item -Path $item.FullName -Recurse -Force
                }
              workingDirectory: '$(Build.SourcesDirectory)'
          - powershell: Get-ChildItem -Force -Path $(Build.SourcesDirectory)
            displayName: 'list gh-pages repo files in sourceDir=$(Build.SourcesDirectory)'
          - script: |
              xcopy "$(Pipeline.Workspace)/docs" "$(Build.SourcesDirectory)" /E /Y
            displayName: 'Copy docs to gh-pages branch'
            workingDirectory: '$(Build.SourcesDirectory)'
          - script: |
              git add .
              git status
              git commit -m "Update documentation from Release-$(Build.SourceBranchName)"
              git push
            displayName: 'Push changes to origin gh-pages branch'
            workingDirectory: '$(Build.SourcesDirectory)'


- stage: 'PublishDebOnGitHubPages'
  displayName: 'Publish deb repository to github pages'
  # dependsOn: PublishGitHubPages
  dependsOn: Build
  condition:  succeeded()
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-24.04'
    environment: publish-github-pages
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: log4TC-deb
          - checkout: deb-repo-repo
            submodules: recursive
            persistCredentials: true
          - script: |
              git config user.email "AutomatedDeploy@bot.com"
              git config user.name "AutomatedDeploy"
              git fetch
              git status
              git branch -a
              git remote -v
              git checkout deb-repo
            displayName: 'checkout deb-repo git repo'
            workingDirectory: '$(Build.SourcesDirectory)'
          - script: |
              echo 'Install aptly'
              sudo apt-get install -qq -y aptly gnupg

              echo 'add deb packages to the repository'
              aptly repo add -config=aptly.conf log4tc $(Pipeline.Workspace)/log4TC-deb/*.deb

              echo 'publish the repository to a local directory'
              aptly publish repo -config=aptly.conf -architectures="amd64,arm64" -skip-signing log4tc

              echo 'The contents of the public directory can then be copied to the staging area'
              cp -r repo/public/ $(Build.ArtifactStagingDirectory)/deb/
            displayName: 'update deb repository with aptly to staging area'
            workingDirectory: '$(Build.SourcesDirectory)/source/aptly'
          - script: |
              git add .
              git status
              git commit -m "Update deb repository from Release-$(Build.SourceBranchName)"
              git push
            displayName: 'Push changes to origin deb-repo branch'
            workingDirectory: '$(Build.SourcesDirectory)'

          - script: |
              git checkout gh-pages
            displayName: 'checkout gh-pages git repo'
            workingDirectory: '$(Build.SourcesDirectory)'

          - script: |
              echo 'clear old deb files in gh-pages branch'
              rm -r $(Build.SourcesDirectory)/deb/
              echo 'The contents of the public directory can then be copied to the gh-pages branch of the github repository'
              cp -r $(Build.ArtifactStagingDirectory)/deb/ $(Build.SourcesDirectory)/deb/
            displayName: 'copy deb repository to gh-pages git repo'
            workingDirectory: '$(Build.SourcesDirectory)'
          - script: |
              git add .
              git status
              git commit -m "Update deb files from Release-$(Build.SourceBranchName)"
              git push
            displayName: 'Push changes to origin gh-pages branch'
            workingDirectory: '$(Build.SourcesDirectory)'
