# Build Trigger
trigger:
  tags:
    include:
      - v*
# not required yet
#  branches:
#    include:
#      - master

# Pull Request Trigger
pr:
  branches:
    include:
      - master
      - dev

# Cake script uses MSBuild .UseToolVersion(MSBuildToolVersion.VS2019)
pool:
  vmImage: 'windows-2019'

#variables:
#  buildConfiguration: 'Release'

# Build steps
steps:
- checkout: self
  submodules: recursive

- task: NuGetToolInstaller@1

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/source/Log4Tc/build.ps1'
    workingDirectory: '$(System.DefaultWorkingDirectory)/source/Log4Tc'

#- task: Cake@2
#  displayName: 'Build with Cake Build tool'
#  inputs:
#    script: 'source/Log4Tc/build.cake'
#    target: 'Default'
#    verbosity: 'Verbose'
#    # is set in build.cake as default to Release
#    #arguments: '-configuration=$(buildConfiguration)'
#    useBuildAgentNuGetExe: true

- task: PublishTestResults@2
  displayName: 'Publish testresult'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/testresults.trx'
    searchFolder: '$(System.DefaultWorkingDirectory)/source/Log4Tc'
    failTaskOnFailedTests: true
  condition: always() # this step will always run, even if the pipeline is canceled

- task: CopyFiles@2
  displayName: 'Copy MSI Setup files'
  inputs:
    Contents: '**/*.msi'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/msi'
    CleanTargetFolder: true
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy generated docfx docs files'
  inputs:
    SourceFolder: 'docs/_site'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/docs'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish MSI Setup files'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/msi'
    ArtifactName: 'msi'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish docs files'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/docs'
    ArtifactName: 'docs'
    publishLocation: 'Container'

