<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="F_LogL3" Id="{8efedc25-279d-4827-9a61-9fd70346530d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogL3 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	stArg1			: T_Arg;
	stArg2			: T_Arg;
	stArg3			: T_Arg;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogTArg(
	eLogLevel, 
	sLogger, 
	sMessage, 
	stArg1, 
	stArg2, 
	stArg3, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	0
);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>