<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="F_LogL7" Id="{f17588ed-6fcc-430b-9223-e0097d9a6647}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogL7 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	stArg1			: T_Arg;
	stArg2			: T_Arg;
	stArg3			: T_Arg;
	stArg4			: T_Arg;
	stArg5			: T_Arg;
	stArg6			: T_Arg;
	stArg7			: T_Arg;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogTArg(
	eLogLevel, 
	sLogger, 
	sMessage, 
	stArg1, 
	stArg2, 
	stArg3, 
	stArg4, 
	stArg5, 
	stArg6, 
	stArg7, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	0
);]]></ST>
    </Implementation>
    <LineIds Name="F_LogL7">
      <LineId Id="7" Count="0" />
      <LineId Id="52" Count="14" />
    </LineIds>
  </POU>
</TcPlcObject>