<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="F_LogL10" Id="{724edc26-86c3-421a-ae1d-be9ae19b7b2f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogL10 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	stArg1			: T_Arg;
	stArg2			: T_Arg;
	stArg3			: T_Arg;
	stArg4			: T_Arg;
	stArg5			: T_Arg;
	stArg6			: T_Arg;
	stArg7			: T_Arg;
	stArg8			: T_Arg;
	stArg9			: T_Arg;
	stArg10			: T_Arg;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogTArg(
	eLogLevel, 
	sLogger, 
	sMessage, 
	stArg1, 
	stArg2, 
	stArg3, 
	stArg4, 
	stArg5, 
	stArg6, 
	stArg7, 
	stArg8, 
	stArg9, 
	stArg10, 
	0
);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>