<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="F_LogL2" Id="{640e86b9-6b82-4437-9981-be1d5c25e259}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogL2 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	stArg1			: T_Arg;
	stArg2			: T_Arg;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogTArg(
	eLogLevel, 
	sLogger, 
	sMessage, 
	stArg1, 
	stArg2, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	Tc2_Utilities.EMPTY_ARG_VALUE, 
	0
);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>