<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Prefer32Bit>false</Prefer32Bit>
    <SelfContained>true</SelfContained>
    <!-- Only supported for .net core app-->
    <PublishSingleFile>false</PublishSingleFile>

    <UserSecretsId>dotnet-Mbc.Log4Tc.Service-A8F619B6-166D-4E1E-9671-59E91544F2C0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="appsettings - Copy.Development.json" />
    <Content Remove="appsettings - Copy.Production.json" />
    <Content Remove="appsettings.Development.json" />
    <Content Remove="appsettings.json" />
    <Content Remove="appsettings.Production.json" />
    <Content Remove="appsettingsInflux.json" />
    <Content Remove="appsettingsSample.json" />
    <Content Remove="appsettingssql.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettingsSql.json" />
    <None Include="appsettingsInflux.json" />
    <None Include="appsettingsSample.json" />
    <None Include="appsettings.Development.json" />
    <None Include="appsettings.json" />
    <None Include="appsettings.Production.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Beckhoff.TwinCAT.Ads" Version="7.0.172" />
    <!-- Activate MQTT with plugin system -->
    <PackageReference Include="Beckhoff.TwinCAT.Ads.AdsOverMqtt" Version="7.0.172" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.*" />
    <PackageReference Include="NLog" Version="5.5.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mbc.Log4Tc.AdsRouter\Mbc.Log4Tc.AdsRouter.csproj" />
    <ProjectReference Include="..\Mbc.Log4Tc.Dispatcher\Mbc.Log4Tc.Dispatcher.csproj" />
    <ProjectReference Include="..\Mbc.Log4Tc.Output.Graylog\Mbc.Log4Tc.Output.Graylog.csproj" />
    <ProjectReference Include="..\Mbc.Log4Tc.Output.InfluxDb\Mbc.Log4Tc.Output.InfluxDb.csproj" />
    <ProjectReference Include="..\Mbc.Log4Tc.Model\Mbc.Log4Tc.Model.csproj" />
    <ProjectReference Include="..\Mbc.Log4Tc.Output.NLog\Mbc.Log4Tc.Output.NLog.csproj" />
    <ProjectReference Include="..\Mbc.Log4Tc.Output.Sql\Mbc.Log4Tc.Output.Sql.csproj" />
    <ProjectReference Include="..\Mbc.Log4Tc.Output\Mbc.Log4Tc.Output.csproj" />
    <ProjectReference Include="..\Mbc.Log4Tc.Receiver\Mbc.Log4Tc.Receiver.csproj" />
    <PackageReference Update="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="InstallService.ps1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="UninstallService.ps1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- Build target to build dep file with: dotnet publish Mbc.Log4Tc.Service\Mbc.Log4Tc.Service.csproj -framework net10.0 - -configuration Release - -self-contained true - -runtime linux-x64 -t:CreateDeb -->
  <ItemGroup>
    <PackageReference Include="Packaging.Targets" Version="0.1.232">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettingsSample.json" CopyToPublishDirectory="PreserveNewest">
      <LinuxPath>/etc/log4tc/config/appsettings.json</LinuxPath>
    </Content>
    <Content Include="../Mbc.Log4Tc.Output.NLog/NLogLinux.config" CopyToPublishDirectory="PreserveNewest">
      <LinuxPath>/etc/log4tc/config/NLog.config</LinuxPath>
    </Content>
    <Content Include="Mbc.Log4Tc.Service.service" CopyToPublishDirectory="PreserveNewest" LinuxFileMode="1755">
      <LinuxPath>/etc/systemd/system/Mbc.Log4Tc.Service.service</LinuxPath>
    </Content>
  </ItemGroup>
</Project>
