<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="F_Log" Id="{000f3ef1-efd9-4a4d-9a1f-6ebbe7a6fe8d}" SpecialFunc="None">
    <Declaration><![CDATA[(*
:Description: Writes the given message at the specific level. 

This function implicit uses the global logger ``Const.sGlobalLogger`` with
the value ``'_GLOBAL_'``.

**Example**

.. code:: 

    F_Log(E_LogLevel.eWarn, 'Something important happened.');
	
*)
FUNCTION F_Log
VAR_INPUT
	eLogLevel		: E_LogLevel;		(* The level of this log. *)
	sMessage		: T_MaxString;		(* The message to log. *)
END_VAR
VAR 
	aEmptyArg		: BYTE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogL(eLogLevel, Const.sGlobalLogger, sMessage);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>