<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="F_Log3" Id="{0aaacd3b-494c-4cb5-ab64-7abdca7ffb13}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Log3 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sMessage		: T_MaxString;
	stArg1			: T_Arg;
	stArg2			: T_Arg;
	stArg3			: T_Arg;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="F_Log3">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>