<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="F_Log3L" Id="{8efedc25-279d-4827-9a61-9fd70346530d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Log3L 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	stArg1			: T_Arg;
	stArg2			: T_Arg;
	stArg3			: T_Arg;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="F_Log3L">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>