<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="F_LogBuilder" Id="{c970aefe-3199-4c53-b630-5acb322a775a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogBuilder : I_LogBuilder
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sMessages		: T_MaxString;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="F_LogBuilder">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>