<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="F_GetTaskContext" Id="{4f3df61f-e1b2-43bf-8e23-325425960015}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_GetTaskContext : I_ContextBuilder

]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetTaskContext := GlobalVariables.aTaskLogger[GETCURTASKINDEXEX()].TaskContext;
]]></ST>
    </Implementation>
    <LineIds Name="F_GetTaskContext">
      <LineId Id="12" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>