<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="IncUDINT" Id="{82f3f8c5-5683-4bda-9a65-aa0bf43ff118}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IncUDINT : UDINT
VAR_INPUT
	refValue		: REFERENCE TO UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IncUDINT := (refValue := refValue + 1);
]]></ST>
    </Implementation>
    <LineIds Name="IncUDINT">
      <LineId Id="7" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>