# Base development image on the .NET version used by Log4TC, adjust if different
FROM mcr.microsoft.com/devcontainers/dotnet:0-7.0-bullseye AS build

# Add any additional setup required for Log4TC here
