# Build Context to this file is ./
#
# Build the image with the following command:
# log4TCversion=$(sed -n 's|.*<Version>\([^<]*\)</Version>.*|\1|p' Directory.Build.props) && \
# podman build \
#   --build-arg BUILD_VERSION="$log4TCversion" \
#   --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
#   --build-arg SOURCECOMMITID="$(git rev-parse HEAD)" \
#   -t log4tc:$log4TCversion-beta .
#
# Run the image with the following command:
# podman run -d --name log4tc -p 16150:16150 log4tc:$log4TCversion-beta

# runtime-deps -> Ubuntu based native linux libs present
FROM mcr.microsoft.com/dotnet/runtime-deps:10.0
ARG BUILD_VERSION
ARG BUILD_DATE
ARG SOURCECOMMITID
WORKDIR /app
# The Log4TC custom ADS server port for this server.
EXPOSE 16150
# The Default ADS Port
EXPOSE 48898

# The OCI Spec Labels https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.opencontainers.image.version=$BUILD_VERSION
LABEL org.opencontainers.image.created=$BUILD_DATE
LABEL org.opencontainers.image.title="log4TC"
LABEL org.opencontainers.image.description="log4TC is a logging and telemetry collection service for TwinCAT systems, providing a unified interface for collecting, processing, and forwarding log data from TwinCAT environments to various logging backends."
LABEL org.opencontainers.image.authors="stegm;bqstony"
LABEL org.opencontainers.image.source="https://github.com/mbc-engineering/log4TC"
LABEL org.opencontainers.image.revision=$SOURCECOMMITID
LABEL org.opencontainers.image.base.name="mcr.microsoft.com/dotnet/runtime:10.0"
LABEL org.opencontainers.image.vendor="mbc-engineering"
LABEL org.opencontainers.image.source="https://github.com/mbc-engineering/log4TC"

# Default configuration for the log4TC service
RUN mkdir -p /var/log/log4tc /etc/log4tc/config
COPY Mbc.Log4Tc.Service/appsettings.json /etc/log4tc/config/appsettings.json
COPY Mbc.Log4Tc.Output.NLog/NLogLinux.config /etc/log4tc/config/NLog.config

# the self-contained build artefact
COPY log4TC-linux-x64/ .
ENTRYPOINT ["./Mbc.Log4Tc.Service"]

