version: '3'

services:
  influxdb:
    image: influxdb:1.8-alpine
    volumes:
      - influxdb:/var/lib/influxdb
      - ./initdb.iql:/docker-entrypoint-initdb.d/initdb.iql
    ports:
      - 8086:8086
  chronograf:
    image: chronograf:1.8-alpine
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
      - 8888:8888
    links:
      - influxdb
    volumes:
      - chronograf:/var/lib/chronograf
  
volumes: 
  influxdb:
  chronograf:
