<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="F_LogLA4C" Id="{9c800fe4-0d98-49dc-a9c3-24715c5105d7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogLA4C 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	aArg1			: ANY;
	aArg2			: ANY;
	aArg3			: ANY;
	aArg4			: ANY;
	iContextBuilder	: I_ContextBuilder;
END_VAR
VAR 
	aEmptyArg		: BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogA(
	eLogLevel,
	sLogger,
	sMessage,
	4,
	aArg1,
	aArg2,
	aArg3,
	aArg4,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	iContextBuilder
);
]]></ST>
    </Implementation>
    <LineIds Name="F_LogLA4C">
      <LineId Id="67" Count="14" />
      <LineId Id="100" Count="0" />
      <LineId Id="82" Count="0" />
      <LineId Id="44" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>