<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="F_LogA8" Id="{19205cbd-a61b-4cc2-b7c8-bc23ef8b0c32}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogA8 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sMessage		: T_MaxString;
	aArg1			: ANY;
	aArg2			: ANY;
	aArg3			: ANY;
	aArg4			: ANY;
	aArg5			: ANY;
	aArg6			: ANY;
	aArg7			: ANY;
	aArg8			: ANY;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogLA8(eLogLevel, Const.sGlobalLogger, sMessage, aArg1, aArg2, aArg3, aArg4, aArg5, aArg6, aArg7, aArg8);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>