<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="F_LogLA2" Id="{8b08c8a6-d948-412c-8a22-c956cd82fb7e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogLA2 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	aArg1			: ANY;
	aArg2			: ANY;
END_VAR
VAR 
	aEmptyArg		: BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogA(
	eLogLevel,
	sLogger,
	sMessage,
	2,
	aArg1,
	aArg2,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg
);
]]></ST>
    </Implementation>
    <LineIds Name="F_LogLA2">
      <LineId Id="60" Count="0" />
      <LineId Id="62" Count="7" />
      <LineId Id="74" Count="5" />
      <LineId Id="61" Count="0" />
      <LineId Id="44" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>