<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="F_LogLA1C" Id="{e5c77183-456e-4052-813a-7b082acaeea7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogLA1C 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	aArg1			: ANY;
	iContextBuilder	: I_ContextBuilder;
END_VAR
VAR 
	aEmptyArg		: BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogA(
	eLogLevel,
	sLogger,
	sMessage,
	1,
	aArg1,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	iContextBuilder
);
]]></ST>
    </Implementation>
    <LineIds Name="F_LogLA1C">
      <LineId Id="67" Count="14" />
      <LineId Id="100" Count="0" />
      <LineId Id="82" Count="0" />
      <LineId Id="44" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>