<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="F_LogLA3C" Id="{517c391a-d776-4625-84c0-0556794529da}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogLA3C 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	aArg1			: ANY;
	aArg2			: ANY;
	aArg3			: ANY;
	iContextBuilder	: I_ContextBuilder;
END_VAR
VAR 
	aEmptyArg		: BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogA(
	eLogLevel,
	sLogger,
	sMessage,
	3,
	aArg1,
	aArg2,
	aArg3,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	iContextBuilder
);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>