<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="F_LogA6" Id="{233402e4-f64a-49dd-8602-39e357cb05f5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogA6 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sMessage		: T_MaxString;
	aArg1			: ANY;
	aArg2			: ANY;
	aArg3			: ANY;
	aArg4			: ANY;
	aArg5			: ANY;
	aArg6			: ANY;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogLA6(eLogLevel, Const.sGlobalLogger, sMessage, aArg1, aArg2, aArg3, aArg4, aArg5, aArg6);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>