<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="F_LogLA3" Id="{60efcf91-d1d3-4f5d-95c9-b1cf38fe1755}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogLA3 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	aArg1			: ANY;
	aArg2			: ANY;
	aArg3			: ANY;
END_VAR
VAR 
	aEmptyArg		: BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogA(
	eLogLevel,
	sLogger,
	sMessage,
	3,
	aArg1,
	aArg2,
	aArg3,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	0
);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>