<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="F_LogLA9C" Id="{babf1963-99b8-458b-af06-fe0a8ebe982a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogLA9C 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	aArg1			: ANY;
	aArg2			: ANY;
	aArg3			: ANY;
	aArg4			: ANY;
	aArg5			: ANY;
	aArg6			: ANY;
	aArg7			: ANY;
	aArg8			: ANY;
	aArg9			: ANY;
	iContextBuilder	: I_ContextBuilder;
END_VAR
VAR 
	aEmptyArg		: BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogA(
	eLogLevel,
	sLogger,
	sMessage,
	9,
	aArg1,
	aArg2,
	aArg3,
	aArg4,
	aArg5,
	aArg6,
	aArg7,
	aArg8,
	aArg9,
	aEmptyArg,
	iContextBuilder
);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>