<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="F_LogLA5C" Id="{6debf689-554a-4e74-984e-9177b252f0c0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogLA5C 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	aArg1			: ANY;
	aArg2			: ANY;
	aArg3			: ANY;
	aArg4			: ANY;
	aArg5			: ANY;
	iContextBuilder	: I_ContextBuilder;
END_VAR
VAR 
	aEmptyArg		: BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogA(
	eLogLevel,
	sLogger,
	sMessage,
	5,
	aArg1,
	aArg2,
	aArg3,
	aArg4,
	aArg5,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	iContextBuilder
);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>