<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="F_LogLA1" Id="{8b962341-2e63-4dbb-a27f-4cb5d658d9ae}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LogLA1 
VAR_INPUT
	eLogLevel		: E_LogLevel;
	sLogger			: T_MaxString;
	sMessage		: T_MaxString;
	aArg1			: ANY;
END_VAR
VAR 
	aEmptyArg		: BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LogA(
	eLogLevel,
	sLogger,
	sMessage,
	1,
	aArg1,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	aEmptyArg,
	0
);
]]></ST>
    </Implementation>
    <LineIds Name="F_LogLA1">
      <LineId Id="60" Count="0" />
      <LineId Id="62" Count="7" />
      <LineId Id="74" Count="5" />
      <LineId Id="90" Count="0" />
      <LineId Id="61" Count="0" />
      <LineId Id="44" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>